# This file was generated by GoReleaser. DO NOT EDIT.
cask "ffgo" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "92fdebfb5280e8cd43384f343ee9f440e79cc7d52a72a0b668aa9dabe9a15364"
      url "https://github.com/arbazkhan971/ffgo/releases/download/v#{version}/ffgo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "36885d7bca85f056961973d779bc94e8cd29dd77377600ef6260017a3a771795"
      url "https://github.com/arbazkhan971/ffgo/releases/download/v#{version}/ffgo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8d9da226a6687409c24d3a67a697bd389da659ed4d65e82eba5acfb6657d69ec"
      url "https://github.com/arbazkhan971/ffgo/releases/download/v#{version}/ffgo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7c8199c67537d8f7d2c34394fa0c49784ca35f86cff3c0a444dd4c6648bbb625"
      url "https://github.com/arbazkhan971/ffgo/releases/download/v#{version}/ffgo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ffgo"
  desc "FFmpeg for humans — inspect, convert, compress and edit video with sane commands"
  homepage "https://github.com/arbazkhan971/ffgo"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on formula: "ffmpeg"

  binary "ffgo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ffgo"]
    end
  end
end
