# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bharatcode < Formula
  desc "BharatCode — an open, sovereign terminal coding agent"
  homepage "https://github.com/arbazkhan971/bharatcode"
  version "0.2.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arbazkhan971/bharatcode/releases/download/v0.2.5/bharatcode_Darwin_x86_64.tar.gz"
      sha256 "c6814638a5fd21529ddda029ee8e560d1cc61c903fea135bdfdbfc6cfb4f6164"

      define_method(:install) do
        bin.install "bharatcode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arbazkhan971/bharatcode/releases/download/v0.2.5/bharatcode_Darwin_arm64.tar.gz"
      sha256 "12cefc8b5a610026b607988bea88594f996fc464caaeefcb7adce1a206a9d00a"

      define_method(:install) do
        bin.install "bharatcode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arbazkhan971/bharatcode/releases/download/v0.2.5/bharatcode_Linux_x86_64.tar.gz"
      sha256 "4e593806d7dfc0c4eb4c99604fe084c33b93cc232eeb2d8e0074c2d17332ef3b"
      define_method(:install) do
        bin.install "bharatcode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arbazkhan971/bharatcode/releases/download/v0.2.5/bharatcode_Linux_arm64.tar.gz"
      sha256 "22bdd235f9c3633bfa990930b67c5ab204e2953542164f46cb9622cf746dc753"
      define_method(:install) do
        bin.install "bharatcode"
      end
    end
  end

  test do
    system "#{bin}/bharatcode", "version"
  end
end
