# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bharatcode < Formula
  desc "BharatCode — an open, sovereign terminal coding agent"
  homepage "https://github.com/arbazkhan971/bharatcode"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arbazkhan971/bharatcode/releases/download/v0.3.0/bharatcode_Darwin_x86_64.tar.gz"
      sha256 "adb1f96a5e93b406b2fbeb7bcae9c6fe63605ce07a4e98f531009462e98fd903"

      define_method(:install) do
        bin.install "bharatcode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arbazkhan971/bharatcode/releases/download/v0.3.0/bharatcode_Darwin_arm64.tar.gz"
      sha256 "52c148d8586828a7aad537e79fb20e5c3e4e709fac3812bf67eb557d6aa43967"

      define_method(:install) do
        bin.install "bharatcode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arbazkhan971/bharatcode/releases/download/v0.3.0/bharatcode_Linux_x86_64.tar.gz"
      sha256 "564d73c0d57a05d9218699c67f46ced4043950c984edb88f9a39e24df4aa76b8"
      define_method(:install) do
        bin.install "bharatcode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arbazkhan971/bharatcode/releases/download/v0.3.0/bharatcode_Linux_arm64.tar.gz"
      sha256 "9c382a3c5fa8629410b816606d13653ac0d58b10dd9a299decc9949986b1ab71"
      define_method(:install) do
        bin.install "bharatcode"
      end
    end
  end

  test do
    system "#{bin}/bharatcode", "version"
  end
end
