# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bharatcode < Formula
  desc "BharatCode — an open, sovereign terminal coding agent"
  homepage "https://github.com/arbazkhan971/bharatcode"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arbazkhan971/bharatcode/releases/download/v0.6.0/bharatcode_Darwin_x86_64.tar.gz"
      sha256 "2943e753889fd05f30ec5ca70a803bf8b72eac76f329cc74dea734a867578bdb"

      define_method(:install) do
        bin.install "bharatcode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arbazkhan971/bharatcode/releases/download/v0.6.0/bharatcode_Darwin_arm64.tar.gz"
      sha256 "a65a5388373afd60a7d07618fcece681dd2cd8b1dc8f9fb5049b9f28cab19778"

      define_method(:install) do
        bin.install "bharatcode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arbazkhan971/bharatcode/releases/download/v0.6.0/bharatcode_Linux_x86_64.tar.gz"
      sha256 "e5c74ab1f88319e93a0ec50adc3ccbddf81c4749672bfa95cb31b7cb69ab158d"
      define_method(:install) do
        bin.install "bharatcode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arbazkhan971/bharatcode/releases/download/v0.6.0/bharatcode_Linux_arm64.tar.gz"
      sha256 "a62cfeaac9c9d1d62933c8e8626596dcd0ef97a5d6304175453f4bec464a2c8e"
      define_method(:install) do
        bin.install "bharatcode"
      end
    end
  end

  test do
    system "#{bin}/bharatcode", "version"
  end
end
